name: Run Playwright Tests on Trigger File Change

on:
  push:
    branches:
      - main
    paths:
      - 'trigger.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}
      CHECKOUT_URL: ${{ secrets.CHECKOUT_URL }}
      FIRST_NAME: ${{ secrets.FIRST_NAME }}
      LAST_NAME: ${{ secrets.LAST_NAME }}
      ZIP_CODE: ${{ secrets.ZIP_CODE }}
      BLOCKED_USER_NAME: ${{ secrets.BLOCKED_USER_NAME }}
      WRONG_PASSWORD: ${{ secrets.WRONG_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # - name: Run Playwright tests
      #   run: npx playwright test --reporter=html 

      # - name: Upload Playwright HTML report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-report
      #     path: playwright-report/

# для сохранения отчета даже при упавших тестах:
  
      - name: Run Playwright tests and generate HTML report
        run: |
            npx playwright test --reporter=html
            echo $? > exit_code.txt

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Fail workflow if tests failed
        run: |
              exit $(cat exit_code.txt)

  